### ISSUE TITLE
Error: Failed to parse beatmap: expected `osu file format v` at file begin

### ISSUE THREAD

**Issue by nyakokitsu** [MaxOhn/rosu-pp-js#5] opened 2024-02-10 17:52 UTC
Error: Failed to parse beatmap: expected `osu file format v` at file begin
https://osu.ppy.sh/osu/2133551

**Comment by MaxOhn** [comment] 2024-02-11 01:49
Works fine for me on map [/b/4488341](https://osu.ppy.sh/beatmapsets/2133551#osu/4488341) (downloaded through <https://osu.ppy.sh/osu/4488341>) which I assume you meant. Maybe your downloaded file is empty potentially due to networking issues?

**Comment by nyakokitsu** [comment] 2024-02-12 15:27
I use an axios to get a file and import into your library through `fromContent`

**Comment by nyakokitsu** [comment] 2024-02-12 15:28
> Works fine for me on map [/b/4488341](https://osu.ppy.sh/beatmapsets/2133551#osu/4488341) (downloaded through https://osu.ppy.sh/osu/4488341) which I assume you meant. Maybe your downloaded file is empty potentially due to networking issues?

Even with your bitmap does not work(

**Comment by MaxOhn** [comment] 2024-02-12 17:08
Does the content of your downloaded file look normal when you open it manually? Its first line should be `osu file format v14`.

**Comment by nyakokitsu** [comment] 2024-02-13 18:34
> Does the content of your downloaded file look normal when you open it manually? Its first line should be `osu file format v14`.

Yes it looks like this

**Comment by MaxOhn** [comment] 2024-02-13 22:53
Can't reproduce it. Perhaps a code snippet could help figuring out your mistake.

**Comment by MaxOhn** [comment] 2024-04-16 15:40
Closing this one, should be resolved with v1.0.0 anyway since beatmap parsing now works differently.

**Closed as completed by MaxOhn** 2024-04-16 15:40 UTC
